languageCode = "zh-cn"
languageName = "简体中文"
weight = 4
title = "Sighthesia's Blog"

[params]
displayName = "简体中文"
isoCode = "zh-cn"
rtl = false
dateFormat = "2006-01-02"
logo = "img/blowfish_logo_transparent.png"
description = "观象Sighthesia的博客"

[params.author]
name = "Sighthesia"
image = "img/9的冻英吉利森_琪露诺.png"
headline = "做自己喜欢的 XD"
bio = "做自己喜欢的 XD"
links = [
  { bilibili = "https://space.bilibili.com/351321394" },
  { github = "https://github.com/Sighthesia" },
  { csdn = "https://blog.csdn.net/ZxeeGX" },
]
